# Generated by Django 4.2.7 on 2024-01-15 22:32

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(default='https://firebasestorage.googleapis.com/v0/b/seawave-d58e4.appspot.com/o/avatar%2Favatar.png?alt=media&token=d042bdf1-e683-4ebc-8d74-1bc8a4fa27a8', upload_to='')),
                ('avatar_url', models.URLField(default='https://firebasestorage.googleapis.com/v0/b/seawave-d58e4.appspot.com/o/avatar%2Favatar.png?alt=media&token=d042bdf1-e683-4ebc-8d74-1bc8a4fa27a8')),
                ('cover_photo', models.ImageField(default='https://firebasestorage.googleapis.com/v0/b/seawave-d58e4.appspot.com/o/cover_photo%2Fphoto_cover.png?alt=media&token=1d034dad-bd80-47e0-8e2a-2e7537bded38', upload_to='')),
                ('cover_photo_url', models.URLField(default='https://firebasestorage.googleapis.com/v0/b/seawave-d58e4.appspot.com/o/cover_photo%2Fphoto_cover.png?alt=media&token=1d034dad-bd80-47e0-8e2a-2e7537bded38')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', related_query_name='customuser', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
