# Generated by Django 4.2.7 on 2023-12-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='../media/avatar.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(default='../media/avatar.png'),
        ),
    ]
