# Generated by Django 4.2.7 on 2024-01-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='../media/avatar.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(default='../media/photo_cover.png', upload_to=''),
        ),
    ]
