# Generated by Django 4.2.7 on 2023-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_alter_customuser_avatar_alter_customuser_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(default='../media/photo_cover.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo_url',
            field=models.URLField(default='../media/photo_cover.png'),
        ),
    ]
