# Generated by Django 4.2.7 on 2023-12-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_alter_customuser_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='https://firebasestorage.googleapis.com/v0/b/seawave-d58e4.appspot.com/o/avatar%2Favatar.png?alt=media&token=d042bdf1-e683-4ebc-8d74-1bc8a4fa27a8', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/seawave-d58e4.appspot.com/o/avatar%2Favatar.png?alt=media&token=d042bdf1-e683-4ebc-8d74-1bc8a4fa27a8'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(default='https://firebasestorage.googleapis.com/v0/b/seawave-d58e4.appspot.com/o/cover_photo%2Fphoto_cover.png?alt=media&token=1d034dad-bd80-47e0-8e2a-2e7537bded38', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/seawave-d58e4.appspot.com/o/cover_photo%2Fphoto_cover.png?alt=media&token=1d034dad-bd80-47e0-8e2a-2e7537bded38'),
        ),
    ]
