# Generated by Django 4.2.7 on 2023-12-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_service', '0004_chatmessage_delete_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='recipient',
        ),
    ]
