# Generated by Django 4.2.7 on 2023-12-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_service', '0003_rename_like_postlike_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='get_media_url',
            field=models.URLField(blank=True),
        ),
    ]
