# Generated by Django 4.2.7 on 2023-12-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_service', '0004_post_get_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='get_media_url',
        ),
    ]
