# Generated by Django 4.2.7 on 2023-12-05 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_service', '0006_post_like_count_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='like_count',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
