# Generated by Django 4.2.7 on 2023-12-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_service', '0007_remove_commentlike_like_count_commentlike_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
